server:
  port: 8080

s3:
  accessKeyId: KM2S7GR01BUER3FKDN0U
  secretAccessKey: MXG3weJGL25Uk3RLkktsZNt1AXwG7pI6tiq7FMnR
  url: https://s3.twcstorage.ru
  region: ru-1
  bucket: 242358d3-d651fce6-3e31-4d69-ab40-fbbcb55e1858
logging:
  level:
    org.springdoc: DEBUG
    org.springframework: DEBUG
    ru.backend: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  cache:
    disabled: true


jwt:
  access-token-key: '{"kty":"oct","k":"hi7S5RX5ZRZooHA0RKGctZ-KtR9FoESgCnH-3BNg5XI"}'
  refresh-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    cookie:
      same-site: none
      secure: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dict_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: updateupdate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  data:
    elasticsearch:
      repositories:
        enabled: true
    redis:
      host: localhost
      port: 6379
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: elastic_password
  cache:
    type: redis
    redis:
      time-to-live: 600000
  mail:
    host: smtp.yandex.ru
    port: 587
    username: kirilenko.konstantyn@yandex.ru
    password: snzvxjglzsiwmpeu
    properties:
      mail:
        debug:
          true
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          localaddress: 0.0.0.0

mailing:
  activation-url: https://sgucrs.ru/activate-account
  email-address-sender: "kirilenko.konstantyn@yandex.ru"
  activation-token-expiration: 3600

elasticsearch:
  index:
    auto-create: true
